name: Main

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  main:
    strategy:
      fail-fast: true
      matrix:
        os: ['ubuntu-18.04']
        python: ['3.7.']

    runs-on: ${{ matrix.os }}

    steps:
      - name: Project checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: make setup

      - name: Check codestyle
        run: make inspect